// Tests for scripts/attribution-check.mjs, run by the Attribution guard workflow before the
// check itself (node --test, no dependencies). Fixtures use a made-up session id.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { classifyLine, findAttribution, stripAttribution, ownerEmails, emailOf } from './attribution-check.mjs'

const SID = 'session_01TESTONLYTESTONLYTESTONLY'
const FOOTER = `_Generated by [Claude Code](https://claude.ai/code/${SID})_`
const ROBOT = '🤖 Generated with [Claude Code](https://claude.com/claude-code)'
const LINK = `https://claude.ai/code/${SID}`

test('flags every known attribution shape', () => {
  const cases = [
    [FOOTER, 'generated-by-footer'],
    [ROBOT, 'generated-by-footer'],
    [LINK, 'session-link-line'],
    [`Claude-Session: ${LINK}`, 'claude-session-trailer'],
    ['Co-authored-by: Claude <noreply@anthropic.com>', 'co-authored-by'],
    ['Co-Authored-By: Claude Opus 4.8 (1M context) <noreply@anthropic.com>', 'co-authored-by'],
    [`see ${LINK} for the run`, 'session-url'],
    [`   ${FOOTER}`, 'generated-by-footer'],
  ]
  for (const [line, rule] of cases) {
    assert.equal(classifyLine(line), rule, line)
    assert.deepEqual(findAttribution(`prose\n\n${line}\n`), [{ lineNo: 3, line: line.trim(), rule }])
  }
})

test('leaves prose, human co-authors and plain links alone', () => {
  for (const line of [
    'no Co-Authored-By trailer, no generated-by footer, no session links in commit messages',
    'Co-authored-by: Ray Smith <ray@example.com>',
    '---',
    'the settings reference at https://code.claude.com/docs/en/settings says',
    '',
  ]) {
    assert.equal(classifyLine(line), null, line)
  }
})

test('strips the footer block the integration appends and keeps the prose', () => {
  const prose = '## Summary\n\nOne paragraph.\n\n## Checklist\n\n- [x] done'
  const r = stripAttribution(`${prose}\n\n${ROBOT}\n\n${LINK}\n\n---\n${FOOTER}`)
  assert.equal(r.changed, true)
  assert.equal(r.body, prose)
  assert.deepEqual(r.leftover, [])
})

test('parses owner emails and commit identities', () => {
  assert.deepEqual(ownerEmails(' Joe-Sladden@hotmail.co.uk, 1+x@users.noreply.github.com ,'),
    ['joe-sladden@hotmail.co.uk', '1+x@users.noreply.github.com'])
  assert.deepEqual(ownerEmails(undefined), [])
  assert.equal(emailOf('Joe Sladden <Joe-Sladden@hotmail.co.uk>'), 'joe-sladden@hotmail.co.uk')
  assert.equal(emailOf('no email here'), '')
})

test('does not flag the rule as CLAUDE.md states it', async () => {
  const { readFileSync } = await import('node:fs')
  const claudeMd = readFileSync(new URL('../CLAUDE.md', import.meta.url), 'utf8')
  assert.deepEqual(findAttribution(claudeMd), [])
})
